### ISSUE TITLE
Enclosure model: -todo-

### ISSUE THREAD

**Issue by Tom-Neverwinter** [mcer12/Nick2-Nixie-Clock#1]
Does the vfd enclosure work as the tubes should be the same?

**Comment by mcer12** [comment]
Sorry, I forgot to add the models... IN-16 is added now, but I suggest the ZM1040 as it looks beautiful! Will add the model later today. https://www.reddit.com/r/esp8266/comments/100mmwy/made_another_esp8266_nixie_clock_atomic_age/

**Comment by mcer12** [comment]
Note that in the IN-16 model, only the smaller transformer will fit.

**Comment by mcer12** [comment]
@Tom-Neverwinter added ZM1040 model to the readme. It's a little bit more complicated to assemble but I highly recommend it.
