### ISSUE TITLE
Component Placement List files

### ISSUE THREAD

**Issue by llamaonaskateboard** [mcer12/Nick2-Nixie-Clock#2]
The README says _"Can be almost completely sourced from LCSC (except for the VFDs of course) and partially assembled using JLCPCB assembly service."_
It appears JLCPCB needs a _Component Placement List (CPL)_ file in order to do this, refer https://jlcpcb.com/help/article/46-Pick-%26-Place-File-for-PCB-Assembly
Are you able to provide these files?

**Comment by mcer12** [comment]
Which one do you plan on making?

**Comment by llamaonaskateboard** [comment]
The IN-16 one

**Comment by mcer12** [comment]
Sorry I totally forgot about this, added.
