### ISSUE TITLE
IN16 - ESP-07S too big for PCB

### ISSUE THREAD

**Issue by kafisc1** [mcer12/Nick2-Nixie-Clock#3]
thank's for this great project. I'm trying to build the IN16 version. JLCPCB informed me, that the ESP-07S ist too big for the PCB design.
On LCSC the ESP-07S is listed with the a size of 16x17x3mm. But if you take a look in the datasheet it is listed with 18x20x3mm.

Would it be possible to use the Wireless-tag WT8266-S3 ESP-07S instead which has a size of 17x16x3mm?

Datasheet for Wireless-tag WT8266-S3 ESP-07S:
[https://datasheet.lcsc.com/lcsc/2001032014_Wireless-tag-WT8266-S3-ESP-07S_C477828.pdf](url)

Datasheet for Ai-Thinker ESP-07S:
[https://datasheet.lcsc.com/lcsc/1810131811_Ai-Thinker-ESP-07S_C82895.pdf](url)

Thaynk you in advance

**Comment by mcer12** [comment]
No, only ESP-M2 or if you want to somehow install external antenna you can use ESP-M1. Also, the IN-16 version comes with a caveat of transformer choice. It's mentioned in the schematic, you can use the very tiny one but you will have to limit the brightness. If you use the larger trasnformer, this goes away but it won't fit in the enclosure. If you're not yet dead set on which one to make, I suggest the ZM1040.

**Comment by kafisc1** [comment]
> No, only ESP-M2 or if you want to somehow install external antenna you can use ESP-M1. Also, the IN-16 version comes with a caveat of transformer choice. It's mentioned in the schematic, you can use the very tiny one but you will have to limit the brightness. If you use the larger trasnformer, this goes away but it won't fit in the enclosure. If you're not yet dead set on which one to make, I suggest the ZM1040.

Thank's for the reply.
I've ordered the Ai-Thinker ESP-07S from LCSC #C82895 and it's not fitting on the PCB. Maybe they changed the size a little bit?
On LCSC the ESP-07S is listed with the a size of 16x17x3mm. But if you take a look in the datasheet it is listed with 18x20x3mm.


![ESP-07S_too_big](https://user-images.githubusercontent.com/56489749/236865863-1ca2e6d2-ef3e-4f79-ba92-3dd3bd2372dd.png)

Thank you in advance
kafisc

**Comment by mcer12** [comment]
You need ESP-M2 or optionally ESP-M1, using a different module will not fit.

**Comment by kafisc1** [comment]
Ok thanks. Then you maybe should adjust  the IN16 BOM.
The ESP-M2 withe the supplier part #C82895 is the ESP I've ordered.
The #C82895 from lcsc is the wrong ESP in the BOM list.





![ESP-07S](https://user-images.githubusercontent.com/56489749/236875127-49cb860c-d05d-4dff-8006-468f7ba9e685.png)

**Comment by mcer12** [comment]
Thanks, it's a "user" footprint from easyeda library because lcsc doesn't have M2 modules for sale. Maybe someone who designed it used ESP-07 as a basis for the model. You should be able to source it on aliexpress.

**Comment by kafisc1** [comment]
> Thanks, it's a "user" footprint from easyeda library because lcsc doesn't have M2 modules for sale. Maybe someone who designed it used ESP-07 as a basis for the model. You should be able to source it on aliexpress.

Thank you very much for your help.
I will close this issue.
