### ISSUE TITLE
Nixie IN-12 display problem!!!

### ISSUE THREAD

**Issue by uongquocthai** [mcer12/Nick2-Nixie-Clock#4]
I used the included *.bin file to download into the ESP. The first time I started the clock, I encountered a problem as shown below, each nixie bulb lit up 3-4numbers inside.  Please help me troubleshoot!! Thanks!!!
![z5067268547006_bfd541bdbcbd5d317f20762a949e665a](https://github.com/mcer12/Nick2-Nixie-Clock/assets/54275934/dbd40e94-04bb-4b97-aae6-be62aba67f5b)
![z5067269172456_90c97e0d94c58d470f0fbb98b361999b](https://github.com/mcer12/Nick2-Nixie-Clock/assets/54275934/9cda8dff-a695-46a8-867a-484f057a7221)

**Comment by mcer12** [comment]
Use genuine SN74141 (or K133ID1) and not fakes from aliexpress.
